spring:
  application:
    name: roundRobin

---
spring:
  config:
    activate:
      on-profile: docker

roundrobin:
  servers:
    - http://echo-1:8080
    - http://echo-2:8080
    - http://echo-3:8080
  
  # Server discovery configuration
  server-discovery-strategy: file            # Using file discovery for Docker
  server-discovery-file-path: servers.txt     # Path to server list file
  
  # Health check configuration
  health-check-interval: 10000        # Health check interval in milliseconds (10 seconds)
  health-check-timeout-seconds: 3     # Timeout for health check requests in seconds
  
  # Performance thresholds
  slow-threshold-ms: 1000             # Threshold to consider a server slow in milliseconds (1 second)
  slowness-cooldown-seconds: 60       # Cooldown period for slow servers in seconds (1 minute)
  initial-latency-ms: 200             # Initial latency assumption for new servers in milliseconds
  
  # Moving average configuration for slowness detection
  slowness-window-size: 5             # Number of recent responses to consider for slowness analysis
  slowness-window-time-ms: 30000      # Time window for slowness analysis in milliseconds (30 seconds)
  slowness-threshold-ratio: 0.6       # Ratio of slow responses required to mark server as slow (60%)
  
  # Request timeout configuration
  request-timeout-seconds: 5          # Timeout for forwarded requests in seconds